version: 2

project_name: ct-hulhu

builds:
  - main: ./cmd/ct-hulhu/
    binary: ct-hulhu
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/TheArqsz/ct-hulhu/internal/runner.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true
